// Generated by CoffeeScript 1.6.2
(function() {
  define([], function() {
    return function() {
      var input;

      input = document.createElement("button");
      input.innerText = "Super Cool Test Button!";
      input.setAttribute("id", "the-button");
      return document.body.appendChild(input);
    };
  });

}).call(this);
