// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'bootstrap'], function($) {
    return {
      bindSearch: function() {
        return $('#search-form').submit(function() {
          var keyWord, redirectUrl;

          keyWord = $("#search-form input:first").val();
          redirectUrl = window.location.protocol + "//" + window.location.host + '/search/';
          if (keyWord) {
            redirectUrl += "q_" + encodeURI(keyWord);
          }
          setTimeout((function() {
            return window.location = redirectUrl;
          }), 1);
          return false;
        });
      }
    };
  });

}).call(this);
