// Generated by CoffeeScript 1.6.2
(function() {
  require.config({
    shim: {
      "bootstrap": {
        deps: ['jquery'],
        exports: "$.fn.popover"
      }
    },
    paths: {
      jquery: 'lib/jquery',
      bootstrap: 'lib/bootstrap'
    }
  });

  requirejs(['jquery', 'common'], function($, common) {
    return $(function() {
      return common.bindSearch();
    });
  });

}).call(this);
