// Generated by CoffeeScript 1.6.2
(function() {
  require.config({
    shim: {
      "bootstrap": {
        deps: ['jquery'],
        exports: "$.fn.popover"
      }
    },
    paths: {
      jquery: 'lib/jquery',
      bootstrap: 'lib/bootstrap'
    }
  });

  requirejs(['jquery', 'bootstrap'], function($, bootstrap) {
    return $(function() {
      return $('#search-form').submit(function() {
        var keyWord, redirectUrl;

        keyWord = $("#search-form input:first").val();
        redirectUrl = window.location.protocol + "//" + window.location.host + '/search/';
        if (keyWord) {
          redirectUrl += "q_" + keyWord;
        }
        setTimeout((function() {
          return window.location = redirectUrl;
        }), 1);
        return false;
      });
    });
  });

}).call(this);
