// Generated by CoffeeScript 1.6.2
(function() {
  require.config({
    shim: {
      "bootstrap": {
        deps: ['jquery'],
        exports: "$.fn.popover"
      }
    },
    paths: {
      jquery: 'lib/jquery',
      bootstrap: 'lib/bootstrap'
    }
  });

  requirejs(['jquery', 'bootstrap'], function($, bootstrap) {
    return $(alert("hello,world!"));
  });

}).call(this);
